x1 = float(input("x1좌표를 입력하시오 : "))
y1 = float(input("y1좌표를 입력하시오 : "))
x2 = float(input("x2좌표를 입력하시오 : "))
y2 = float(input("y2좌표를 입력하시오 : "))
print("두 점의 거리:", (((x1 - x2) ** 2) + ((y1 - y2) ** 2)) ** (1 / 2))
